# Generated by Django 6.0.6 on 2026-07-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='address',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
