# Generated by Django 6.0.6 on 2026-07-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_userdetails_address_userdetails_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='pic',
            field=models.ImageField(default='user.png', upload_to='uploads/'),
        ),
    ]
