# Generated by Django 6.0.6 on 2026-07-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_alter_userdetails_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='users/'),
        ),
    ]
