# Generated by Django 6.0.6 on 2026-07-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='cimg',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pimage',
            field=models.ImageField(default='default.jpg', upload_to='products/'),
        ),
    ]
