# Generated by Django 6.0.6 on 2026-07-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_categorymodel_cimg_alter_productmodel_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='cname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
