# Generated by Django 6.0.6 on 2026-07-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
