# Generated by Django 6.0.6 on 2026-07-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
